[google_sheets]
sheet_id = "192etQQagcQv-RHFopzr1lm1UBDKXRKZyesGSzNtrWcw"

[openai]
api_key = "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"